### ISSUE TITLE
feature: Make this project easier to consume via dedicated web-app

### ISSUE THREAD

**Issue by geoand** [snowdrop/k8s-infra#135]
Although this github project provides a lot of features covering a lot of needs such as creating docker machines using minishift, vagant, openstack, ..., it nevertheless places a heavy burden on users who need: 
- To have ansible installed locally like also the the proper version and 
- To read through various README files to know which playbooks to execute: istio, halkyon, tekton, ....

To make it easier for (approved users) to create dedicated clusters on Hetzner - https://www.hetzner.com/cloud, we could create : 
- A web application that would give the ability to either:
  - create/launch/delete a VM on Hetzner Cloud or
  - Leveraging an existing one to install a Kubernetes or Openshift cluster.
The application would then delegate to the playbooks and send an email to the user when the cluster is ready.

_Pros_: No need for users to have to have anything installed locally or the credentials to access _cloud.hetzner.com_. With the proper UI, the cluster could be customizable to fit their needs.

Cons: Such an app would need to be developed and maintained

**Comment by jacobdotcosta** [comment]
If I understand correctly, we're looking for a tool to execute playbooks. If this the case we have [AWX](https://github.com/ansible/awx), which is the upstream project for [Ansible Tower](https://www.ansible.com/products/tower). We could have it installed on a server, which would get the playbooks and roles updated from a git repository.

**Comment by cmoulliard** [comment]
Can you make a demo please as it seems for me that this application is complex ? @jacobdotcosta

**Comment by cmoulliard** [comment]
As we have now an Ansible tower app able to deal with the ideas reported here, we can close it.
