### ISSUE TITLE
Use of host_vars or group_vars to define the vm server variables

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/k8s-infra#139]
Instead of using extra vars in the hetzner playbooks we should think about getting them from the inventory, using group and host vars.

**Comment by cmoulliard** [comment]
Can you then provide an example starting from a `playbook inventory/xxx.yml -e -e -e -e ` command example and how it should looks like if you move them within the inventory file ?

**Comment by jacobdotcosta** [comment]
All storable variables, and non local ones such as the context name, could be added to the inventory.
```bash
$ ansible-playbook playbook/hetzner-create-hcloud-server.yml -e salt_text=mysalt -e password_text=mypass -e hetzner_context_name=mycontext -e vm_delete=true
```
The inventory host vars would be something like:
```
vm_image: myname
server_type: cx31
vm_image: centos-7
```
... as well as other variables such as the version of kubernetes to be installed. Because inventory should not uploaded to github, we also required a way to generate the inventory from hetzner using ansible dinamic intentory or generating it on demand using custom playbook.

**Comment by cmoulliard** [comment]
To be closed with your PR I think ? @jacobdotcosta

**Comment by jacobdotcosta** [comment]
> To be closed with your PR I think ? @jacobdotcosta

We just scratched the surface around this. Today we had to go back to discussing this subject. Now that we're moving to a dynamic ansible inventory #148 , I think we have to rethink the strategy. I would leave it open for now.
