### ISSUE TITLE
Deploy snowdrop-bot to our prod cluster

### ISSUE THREAD

**Issue by iocanel** [snowdrop/k8s-infra#143]
The project lives here: https://github.com/snowdrop-bot/snowdrop-bot

It should be deployed on our prod cluster.

- [ ] Create persistent volume for  database
- [ ] Create a secret to host `config.json` for Google Docs API access
- [ ] Tune everything missing from the generated manifests
- [ ] Perform the actual container build
- [ ] Provide feedback on how to improve generated manifests.

Note: In Quarkus 1.3 there are  a lot of new things around building container-images and Kubernetes, and could possibly simplify the whole process.

**Comment by cmoulliard** [comment]
`Provide feedback on how to improve generated manifests.` -> What do you want to do here ?
`Perform the actual build` -> container image build you mean ? 
`Tune everything missing from the generated manifests` -> Where such generated manifest are coming from ?

@iocanel

**Comment by iocanel** [comment]
@cmoulliard: The manifests are generated from the Quarkus Kubernetes extension. This is why feedback is requested, so that we can further improve it.

**Comment by jacobdotcosta** [comment]
This task has been discussed on other issues:
* https://github.com/snowdrop-bot/snowdrop-bot/issues/90
* https://github.com/snowdrop-bot/snowdrop-bot/issues/78
* ...
