### ISSUE TITLE
Some changes are needed to install k8s

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#147]
## Enhancement

Some changes are needed to install k8s as we need the following VARS defined within the `vars_host/<vm_name>` file

```
ip_address: 116.203.41.7
public_ip_address: 116.203.41.7
ansible_ssh_port: 47286
```

**Comment by jacobdotcosta** [comment]
This issue included other tasks such as adding `become: yes` to ansible tasks that required being ran using root. This was required now that `root` is not used by default user in ansible playbooks.
