### ISSUE TITLE
Improvements to the Ansible inventory

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/k8s-infra#148]
- [x] Include a description on the inventory folder structure and add sample data.
- [x] Build a dynamic inventory from pass

**Comment by cmoulliard** [comment]
> * Generate the inventory from passstore

Is it already done ?

**Comment by jacobdotcosta** [comment]
> > * Generate the inventory from passstore
> 
> Is it already done ?

No, I have to finish the 2nd task.

**Comment by jacobdotcosta** [comment]
Also, should we move these playbooks to the `/k8s-infra/kubernetes/ansible` folder and merge with the existing `k8s.yml` file existing there?

**Comment by cmoulliard** [comment]
> Also, should we move these playbooks to the `/k8s-infra/kubernetes/ansible` folder

Which playbooks ?

**Comment by cmoulliard** [comment]
Did you created a PR or issue describing `Build a dynamic inventory from pass` ? @jacobdotcosta

**Comment by jacobdotcosta** [comment]
> Did you created a PR or issue describing `Build a dynamic inventory from pass` ? @jacobdotcosta

Yes, it's PR #154
