### ISSUE TITLE
[Question] How should we generate the roles's documentation ?

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#151]
## Questions

- [ ] How should we generate the roles's documentation (using a template. ...) ?
- [ ] Should we create one roles doc page as we have [here](https://github.com/snowdrop/k8s-infra/blob/3b118fda003376d403e5aaf1b512f3ea057f6fa0/doc/post-installation.md#L121)  ?

@jacobdotcosta

**Comment by jacobdotcosta** [comment]
> ## Questions
> * [ ]  How should we generate the roles's documentation (using a template. ...) ?
> * [ ]  Should we create one roles doc page as we have [here](https://github.com/snowdrop/k8s-infra/blob/3b118fda003376d403e5aaf1b512f3ea057f6fa0/doc/post-installation.md#L121)  ?
> 
> @jacobdotcosta

Yes, and yes. 

I think we should have a main document listing the existing roles and an overview as in your example. And roles can be documented using a template, in the roles I created there's a `README.md` that can be used as template.

**Comment by jacobdotcosta** [comment]
A template can be obtained from `ansible-galaxy` using the following statement. 
```bash
$ ansible-galaxy init test-role-1
```
It creates a new Ansible Galaxy role, which is not the goal, but generates a README.md that we could use as template. It looks something like this.
```yaml
Role Name
=========

A brief description of the role goes here.

Requirements
------------

Any pre-requisites that may not be covered by Ansible itself or the role should be mentioned here. For instance, if the role uses the EC2 module, it may be a good idea to mention in this section that the boto package is required.

Role Variables
--------------

A description of the settable variables for this role should go here, including any variables that are in defaults/main.yml, vars/main.yml, and any variables that can/should be set via parameters to the role. Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.) should be mentioned here as well.

Dependencies
------------

A list of other roles hosted on Galaxy should go here, plus any details in regards to parameters that may need to be set for other roles, or variables that are used from other roles.

Example Playbook
----------------

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:

    - hosts: servers
      roles:
         - { role: username.rolename, x: 42 }

License
-------

BSD

Author Information
------------------

An optional section for the role authors to include contact information, or a website (HTML is not allowed).
```
More information on how to create a new role in the [Ansible Docs pages](https://galaxy.ansible.com/docs/contributing/creating_role.html).

**Comment by cmoulliard** [comment]
What is the command then to be used to generate doc from an existing role @jacobdotcosta ?

**Comment by jacobdotcosta** [comment]
> What is the command then to be used to generate doc from an existing role @jacobdotcosta ?

I don't know of any. The best option is to create a new README.md from the default template and start from there.

**Comment by cmoulliard** [comment]
Can you create a README.md template, something maybe mixing what the command `ansible-galaxy init xxxx` generates and what we used as convention within this project ? @jacobdotcosta 

Idea

```
### Command : <role_name>

  <example of command with parameters>
  ``bash
  ansible-playbook -i inventory/cloud_host playbook/post_installation.yml \
     -e openshift_admin_pwd=admin \
     --tags "enable_cluster_role"
  ``
 <Description> 
 The `enable_cluster_role` role also accepts the following parameters that can be added using Ansible's `extra-vars` [syntax](http://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#passing-variables-on-the-command-line):
  
<Table of parameters> 
| Name | Description  | Default
| --------- | ------------ | ------------ |
| cluster_role_name | The name of the cluster role to grant to the admin user | cluster-admin  
| user | The user to which to grant the cluster role | admin  
| openshift_admin_pwd | The password of the admin user | 
```

**Remark**: Next we will see how we could generate within the project documentation a TOC pointing to the different roles and including such columns : 

- Role Name + link
- Description: Short summary about what the role is doing
- Cluster	type: okd, k8s
- Tag: labels description the category to which the role belongs

**Comment by cmoulliard** [comment]
I created an asciidoctor extension which can do the job to fill the table with the Roles discovered within the different role asciidoctor file

Code: https://github.com/cmoulliard/playbook-doc/blob/8a1c1913bff6dc8648c100a203f415f193c89d8a/src/main/java/dev/snowdrop/extension/CreateTableTreeProcessor.java#L16
Example of what is generated : https://htmlpreview.github.io/?https://raw.githubusercontent.com/cmoulliard/playbook-
doc/59f48f31f23ce6069bc3f14ad5da66ae95be4265/asciidoctor/all.html

WDYT @jacobdotcosta ?

**Comment by cmoulliard** [comment]
Question: should we use a macro to specify metadata information as by example the cluster's type that a role could target ? @jacobdotcosta 

Current example
```
== Command: Role Name 1

Cluster target type: K8s
```
Proposition
```
[cluster_type=ocp]
== Command: Role Name 1

....
```
