### ISSUE TITLE
Deploy snowdrop-bot on production

### ISSUE THREAD

**Issue by iocanel** [snowdrop/k8s-infra#155]
The code of the bot is here: https://github.com/snowdrop-bot/snowdrop-bot

The project can be build with `mvn clean install`
After the installation kubernetes manifests will be found under `target/kubernetes/kubernetes.yml`.

Additional configuration required:

1. A PV volume with claim name `snowdrop-bot-claim`.
2. A secret named github-secrets containing at least the `GITHUB_TOKEN` property.
3. A secret named googledocs-secret containing the config.json file required to access googledocs via java.

**Comment by iocanel** [comment]
This issue is currently blocked by https://github.com/snowdrop-bot/snowdrop-bot/issues/47

**Comment by cmoulliard** [comment]
Where do you currently run this snowdrop bot k8s application @iocanel ?

**Comment by iocanel** [comment]
> Where do you currently run this snowdrop bot k8s application @iocanel ?

Mostly on my laptop!
But at some point I had it running on our 3.11 cluster on hetzner.

**Comment by cmoulliard** [comment]
> Mostly on my laptop!

Can you share the k8s generated to deploy the project please ? @iocanel

**Comment by jacobdotcosta** [comment]
I think this task is done! WDYT @iocanel @cmoulliard ?
