### ISSUE TITLE
Build quarkus application to manage requests and vm and app inventory

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/k8s-infra#157]
Create a quarkus application to manage the workflow of vm hosts such as:
- [ ] Manage requests of hosts and applications
- [ ] Manage the existing hosts, applications, versions, etc
- [ ] Provide the Ansible inventory functionality for playbook execution

**Comment by cmoulliard** [comment]
Do we still need this ticket ? @jacobdotcosta
