### ISSUE TITLE
Missing Red Hat Certificates

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/k8s-infra#171]
## Issue

I get an error when trying to pull the openjdk image on the ocp3 hetzner cloud machine:
```
docker pull registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest
Trying to pull repository registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift ...
open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory
```

## Workaround

Problem fixed after executing this command -> `openssl s_client -showcerts -servername registry.access.redhat.com -connect registry.access.redhat.com:443 </dev/null 2>/dev/null | openssl x509 -text > /etc/rhsm/ca/redhat-uep.pem on the ocp3 centos vm`

## Discussion
There is a bugzilla ticket discussing this problem : https://bugs.centos.org/view.php?id=14785

**Comment by cmoulliard** [comment]
Can we close this ticket or do you expect something else @aureamunoz ?

**Comment by aureamunoz** [comment]
I think we can close it.
