### ISSUE TITLE
Upgrade the Kubernetes cluster on Hetzner machine

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#177]
## Proposition

The version of the Kubernetes cluster deployed on the dedicated Hetzner machine is a bit outdated and should be upgraded to a more recent which supports to renew automatically k8s certificate, ..... 

```
kc get node/centos-77-64-minimal
NAME                   STATUS   ROLES    AGE    VERSION
centos-77-64-minimal   Ready    master   405d   v1.14.9
```

As `kubeadm` client proposes a command in order to upgrade an existing cluster, we should detail here how such a process could take place (example: do we have to backup before to upgrade, can we do a dry-run such as : kubeadm upgrade apply --dry-run, ...) ?

*References*:
- https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/
- https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
- https://www.linuxsysadmins.com/upgrade-kubernetes-cluster/

WDYT ? @jacobdotcosta

**Comment by jacobdotcosta** [comment]
I think we should either have a backup of that server prior to launching the migration process, or clone it onto a dev host to test the migration process.

**Comment by cmoulliard** [comment]
> a backup of that server

Making a backup of a k8s cluster is not so easy. What do you suggest (if needed) as strategy ?

**Comment by cmoulliard** [comment]
> or clone it onto a dev host to test the migration process.

Again. Not so easy to be done. We need the advise of K8s Ops expert for that ;-)

**Comment by cmoulliard** [comment]
FYI

```
CentOS-77-64-minimal:~$ kubeadm upgrade plan
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.14.9
[upgrade/versions] kubeadm version: v1.14.9
I0128 11:59:09.863122    1125 version.go:240] remote version is much newer: v1.20.2; falling back to: stable-1.14
[upgrade/versions] Latest stable version: v1.14.10
[upgrade/versions] Latest version in the v1.14 series: v1.14.10

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT       AVAILABLE
Kubelet     1 x v1.14.9   v1.14.10

Upgrade to the latest version in the v1.14 series:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.14.9   v1.14.10
Controller Manager   v1.14.9   v1.14.10
Scheduler            v1.14.9   v1.14.10
Kube Proxy           v1.14.9   v1.14.10
CoreDNS              1.3.1     1.3.1
Etcd                 3.3.10    3.3.10

You can now apply the upgrade by executing the following command:

	kubeadm upgrade apply v1.14.10

Note: Before you can perform this upgrade, you have to update kubeadm to v1.14.10.
```

**Comment by jacobdotcosta** [comment]
I was thinking about install another k8s `1.14` cluster and deploying our applications over there.

Having removed the pods in the `cert-manager`, `kube-system` and `kubernetes-dashboard` namespaces we'd *"only"* have to deploy these:

```
NAMESPACE              NAME                                           READY   STATUS    RESTARTS   AGE
bot                    snowdrop-bot-869bc47486-hm5rf                  1/1     Running   3          80d
halkyon-site           halkyon-nginx-8c479974d-wwsbb                  1/1     Running   4          405d
snowdrop-site          snowdrop-site-angular-774dd56856-89p6x         1/1     Running   4          405d
snowdrop-site          spring-boot-generator-6587865b98-qspx4         1/1     Running   3          246d
```

**Comment by jacobdotcosta** [comment]
> FYI
> 
> ```
> CentOS-77-64-minimal:~$ kubeadm upgrade plan
> [preflight] Running pre-flight checks.
> [upgrade] Making sure the cluster is healthy:
> [upgrade/config] Making sure the configuration is correct:
> [upgrade/config] Reading configuration from the cluster...
> [upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
> [upgrade] Fetching available versions to upgrade to
> [upgrade/versions] Cluster version: v1.14.9
> [upgrade/versions] kubeadm version: v1.14.9
> I0128 11:59:09.863122    1125 version.go:240] remote version is much newer: v1.20.2; falling back to: stable-1.14
> [upgrade/versions] Latest stable version: v1.14.10
> [upgrade/versions] Latest version in the v1.14 series: v1.14.10
> 
> Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
> COMPONENT   CURRENT       AVAILABLE
> Kubelet     1 x v1.14.9   v1.14.10
> 
> Upgrade to the latest version in the v1.14 series:
> 
> COMPONENT            CURRENT   AVAILABLE
> API Server           v1.14.9   v1.14.10
> Controller Manager   v1.14.9   v1.14.10
> Scheduler            v1.14.9   v1.14.10
> Kube Proxy           v1.14.9   v1.14.10
> CoreDNS              1.3.1     1.3.1
> Etcd                 3.3.10    3.3.10
> 
> You can now apply the upgrade by executing the following command:
> 
> 	kubeadm upgrade apply v1.14.10
> 
> Note: Before you can perform this upgrade, you have to update kubeadm to v1.14.10.
> ```

What does `remote version is much newer: v1.20.2; falling back to: stable-1.14` mean, that it will only upgrade to `1.14.10`?

**Comment by cmoulliard** [comment]
> What does `remote version is much newer: v1.20.2; falling back to: stable-1.14` mean, that it will only upgrade to `1.14.10`?

Existing documentation always refers as migration path `1.14 -> 1.15 or 1.15 -> 1.16, ...` but no big jump from `1.14 to 1.18` - https://v1-16.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by cmoulliard** [comment]
The following bash script could be used to do the rollout

```
#!/bin/bash

# declare -a Versions=("1.14.10" "1.15.15" "1.16.15" "1.17.17" "1.18.15" "1.19.7" "1.20.2")
declare -a Versions=("1.19.7" "1.20.2")
MASTER=centos7.localdomain

for VERSION in ${Versions[@]}; do
   echo "K8s version to be upgraded to : $VERSION"
   sudo yum install -y kubeadm-$VERSION --disableexcludes=kubernetes
   sudo kubeadm upgrade apply v$VERSION -y
   sudo kubectl --kubeconfig=.kube/config drain $MASTER --ignore-daemonsets --delete-local-data
   sudo yum install -y kubelet-$VERSION kubectl-$VERSION --disableexcludes=kubernetes
   sudo systemctl daemon-reload
   sudo systemctl restart kubelet
   sudo kubectl --kubeconfig=.kube/config uncordon $MASTER
done
```

**Comment by cmoulliard** [comment]
I started the process and migrated the K8s cluster from 1.14 to 1.15.

**Comment by cmoulliard** [comment]
During the upgrade from 1.15 to 1.16, the following error was reported by the node `kubectl get node/centos-77-64-minimal -o yaml`
```
network plugin is not ready: cni config uninitialized
```

The fix, as described here:  https://github.com/kubernetes/kubernetes/issues/48798 has been to apply the following resource
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
```

**Comment by cmoulliard** [comment]
Following issue has been experimented during upgrade from 1.16 to 1.17
```yaml
- lastHeartbeatTime: "2021-05-17T12:23:34Z"
    lastTransitionTime: "2021-05-17T12:15:08Z"
    message: 'Failed to initialize CSINode: error updating CSINode annotation: timed
      out waiting for the condition; caused by: the server could not find the requested
      resource'
    reason: KubeletNotReady
    status: "False"
```
and fixed with: https://rahulschoudhari.wordpress.com/2020/06/16/kubeletnotready-failed-to-initialize-csinode/

@jacobdotcosta : FYI.

**Comment by cmoulliard** [comment]
Cluster has been successfully migrated to version `1.19.11` today. FYI: @aureamunoz @iocanel @jacobdotcosta @gytis @metacosm 
Can you check if web site, bot, ... are working correctly ?
