### ISSUE TITLE
Add a condition to test if passstore can be used to get the token/pwd

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#185]
## Feature request

The existing code, deploying the kubernetes dashboard , ely on the fact that `passstore` is installed and that the following parameters exist `token_public` and `token_secret` : 

https://github.com/snowdrop/k8s-infra/blob/cd5d9d58c8098cf90b2c105852c7bf62b0c73b94/ansible/roles/k8s_dashboard/tasks/install.yml#L3-L10

As this role could be used to install the dashboard locally, on a machine where the parameters to create the VM were not stored using passstore, then we should offer an option to pass the token information as `-e token_public` and `-e token_secret`.

BTW, as such a token can be fetched from the k8s cluster using this command `kubeadm token`, this is perhaps another approach that we could use to get the information.

**Comment by cmoulliard** [comment]
FYI, the command fails to execute `pass` within the VM

```
TASK [k8s_dashboard : Generate k8s dasbboard tokens] ******************************************************************************************************************************************************
task path: /Users/cmoullia/.ansible/collections/ansible_collections/snowdrop/k8s-infra/k8s_dashboard/tasks/install.yml:2
redirecting (type: lookup) ansible.builtin.passwordstore to community.general.passwordstore
Loading collection community.general from /usr/local/Cellar/ansible/2.10.5/libexec/lib/python3.9/site-packages/ansible_collections/community/general
fatal: [127.0.0.1]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'passwordstore'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Command '['pass', 'insert', '-f', '-m', 'virtualbox/centos7/k8s_dashboard_token_public']' returned non-zero exit status 1."
}
```

**Comment by cmoulliard** [comment]
Got it !!! Can you please document that a plugin/module should be first installed as prereq using this command
```
ansible-galaxy collection install community.general
```
as we are using this plugin : https://docs.ansible.com/ansible/latest/collections/community/general/passwordstore_lookup.html#ansible-collections-community-general-passwordstore-lookup

**Comment by jacobdotcosta** [comment]
Are you launching this playbook from the VM itself? This playbook is designed to be called from our PCs where passwordstore is installed. I never launched it from the host/server.

**Comment by cmoulliard** [comment]
> Are you launching this playbook from the VM itself?

No. From my macbook machine

**Comment by cmoulliard** [comment]
When passstore is not needed, we could easily generate the `public.secret` token according to this [rule](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-token/#synopsis) : 

```
You don't have to use this command in order to generate a token.
You can do so yourself as long as it is in the format "[a-z0-9]{6}.[a-z0-9]{16}".
This command is provided for convenience to generate tokens in the given format.

You can also use "kubeadm init" without specifying a token and it will generate and print one for you.
```
