### ISSUE TITLE
Improve role installing docker like kubernetes

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#215]
## Improvement

The current `k8s_cluster` role install a k8s cluster within a VM but also docker (see docker.yml file) and containerd (see `install_containerd.yml` and `remove_containerd.yml` files).

I propose to move the `docker` and `containerd` tasks to new roles: k8s_docker and k8s_containerd (or maybe that we merge then into one - WDYT @jacobdotcosta ) and also to improve how to install docker as we need someadditional packages like also to add the user to the group

```
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum list installed | grep docker
sudo yum -y remove docker-ce.x86_64
sudo yum -y remove docker-ce-cli.x86_64
sudo yum -y remove containerd.io.x86_64

sudo yum install docker-ce docker-ce-client containerd
sudo systemctl enable docker
sudo systemctl start docker
sudo gpasswd -a snowdrop docker
sudo reboot
```

**Comment by jacobdotcosta** [comment]
Could we call the resulting roles only `docker` and `containerd` ?

There's already 1 role called `docker` that doesn't have the docker installation, do you know what's about? Could we include it inside the new `docker` role

@cmoulliard ?

**Comment by cmoulliard** [comment]
> There's already 1 role called `docker` that doesn't have the docker installation, do you know what's about?

This role was created a couple of months ago to configure docker deployed on a VM. This is the reason why it contains `insecure-registries` section and `iptables` in order to access it from an external machine. 

If we keep this role, then it should certainly be renamed and better documented: https://github.com/snowdrop/k8s-infra/blob/master/ansible/roles/docker/README.adoc

**Comment by cmoulliard** [comment]
> Could we include it inside the new `docker` role

I think that we should have separate roles; one to install/remove docker and/or containerd and another to expose the docker daemon as `tcp://0.0.0.0:2376`
