### ISSUE TITLE
Have a container image packaging ansible, tools + k8s-infra (or galaxy collection) 

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#246]
The container should have loaded the following information/tools:
* ansible >= 2.10
* pass
* git
* openvpn (to connect to the RH network without the need for the host to be connected to the VPN)
* RH VPN configured 
* Ansible collections:
  * openstack.cloud
* pip packages:
  * decorator
  * openstacksdk

Should mount volumes from the host regarding:
* passwordstore database 
  * otherwise github and GPG information requires to be passed to the container wich might make it more difficult to configure and use.
* k8s-infra

Should have the following environment variables
* vpn host, vpn user and vpn password
  * if these 3 parameters are provided when executing commands against the container a VPN tunnel would be established prior to opening the connection

## Requirement

Have a container image packaging ansible, tools, some aliases (to create/delete VM, deploy k8s) & k8s-infra (or maybe move it as a galaxy collection. WDYT @jacobdotcosta )

Example
```
FROM centos:7

ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN yum check-update; \
    yum install -y gcc libffi-devel python3 epel-release; \
    yum install -y python3-pip; \
    yum install -y wget; \
    yum clean all

RUN pip3 install --upgrade pip; \
    pip3 install --upgrade virtualenv; \
    python3 -m pip install ansible
```

Command to be used to build/run it
```
docker build . -t ansible
docker run -it ansible
```

**Comment by jacobdotcosta** [comment]
I had created [this issue](https://github.com/snowdrop/team/issues/737) to document the contents of the container which I was building. Could you take a look at it?

**Comment by jacobdotcosta** [comment]
Deploying on AWX

Successes so far:
  - Full deploy of VM on OpenStack, with securization
  - Created shared user to be used on all VM

Current issues are:
  - Add shared SSH key to custom OS user
  - k8s installation alignment
  - Test Hetzner deployment
