### ISSUE TITLE
node.kubernetes.io/disk-pressure reported on centos8 k8s 1.21 cluster : 10.0.76.43

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#249]
## To be investigated

Pod was not started due to `Warning  FailedScheduling  4s    default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/disk-pressure: }, that the pod didn't tolerate.`

Here is what I did: https://medium.com/sestek/how-to-fix-kubernetes-node-kubernetes-io-disk-pressure-taint-ca32f90bd4c

**Comment by jacobdotcosta** [comment]
Should we increase the installation disk size from 40GB to 60GB?

**Comment by cmoulliard** [comment]
Not sure as we must first understand what is the root cause of the message.
