### ISSUE TITLE
Use ~/.bash_aliases file

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#258]
## Feature request

Most of the aliases that we are developing are mainly created under the file `~/.bash_aliases`. Of course the content is erased when a new VM is created.

Would it be possible to add, part of the `~/.bash_aliases` file such a code

```
if [ -f ~/.bash_aliases ]; then
        . ~/.bash_aliases
fi
```

 in order to let to provision the aliases within the file
`~/.bash_aliases` ?

WDYT ? @jacobdotcosta @BarDweller

**Comment by jacobdotcosta** [comment]
I totally agree with it as I use this mechanism on my workstations.

After creating the `.bash_alias`, adding the following code to the `.bashrc` file, as you suggested, makes the alias available on any session.

```bash
# User specific environment
if [ -f ~/.bash_alias ]; then
    . ~/.bash_alias
fi
```

**Comment by cmoulliard** [comment]
> adding the following code

Can you then create a PR to make this change for all the VMs created ? @jacobdotcosta
