### ISSUE TITLE
Test kind multi-cluster

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/k8s-infra#286]
Test the kind deployment script for multi-cluster deployments.
- [x] multiple ingress controllers and port mappings

**Comment by cmoulliard** [comment]
> Test the kind deployment script for multi-cluster deployments.

Can you elaborate this point please as this is not clear what you want to do ? Do you want to support using the ash script to create several nodes instead of one by default ? @jacobdotcosta
