### ISSUE TITLE
What about the empty requirements.txt file and roles/collections folder ?

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#325]
## Question

Why do we have an empty requirements.txt file ? Is it needed and used ?
What is the purpose of the `./roles` folder ?

![Screenshot 2023-06-14 at 11 24 17](https://github.com/snowdrop/k8s-infra/assets/463790/8b9d9235-d74c-4965-ac4d-4bea35652553)

What is also the goal of the `./collections` folder ?
![Screenshot 2023-06-14 at 12 05 42](https://github.com/snowdrop/k8s-infra/assets/463790/7cff264b-752f-420a-904c-0092cd1ce4e8)

**Comment by jacobdotcosta** [comment]
Those folders contain requirements for the project. One declares the Ansible Collections that are needed by the project and the other the role requirements. Since the `roles/requirements.yml` file is empty I think we could remove it.

**Comment by cmoulliard** [comment]
> I think we could remove it.

Go ahead and remove it then @jacobdotcosta
